name: "todo-server"
services:
  api:
    build: .
    command:
      - ./bin/todo-server-linux
    ports:
      - 3001:8080
    environment:
      MONGO_HOST: mongo
      MONGO_USER: admin
      MONGO_PASS: password
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 3002:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password